config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :neighborhoods

      resources :cuisines

      resources :users

      resources :very_bests

      resources :venues

      resources :dishes
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dishes#index"
  resources :neighborhoods
  resources :cuisines
  devise_for :users
  resources :users
  resources :very_bests
  resources :venues
  resources :dishes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/very_best.rb
class VeryBest < ApplicationRecord
  # Direct associations

  belongs_to :user

  belongs_to :venue

  belongs_to :entree,
             class_name: "Dish",
             foreign_key: "dish_id"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    notes
  end
end

app/controllers/api/v1/very_bests_controller.rb
class Api::V1::VeryBestsController < Api::V1::GraphitiController
  def index
    very_bests = VeryBestResource.all(params)
    respond_with(very_bests)
  end

  def show
    very_best = VeryBestResource.find(params)
    respond_with(very_best)
  end

  def create
    very_best = VeryBestResource.build(params)

    if very_best.save
      render jsonapi: very_best, status: :created
    else
      render jsonapi_errors: very_best
    end
  end

  def update
    very_best = VeryBestResource.find(params)

    if very_best.update_attributes
      render jsonapi: very_best
    else
      render jsonapi_errors: very_best
    end
  end

  def destroy
    very_best = VeryBestResource.find(params)

    if very_best.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: very_best
    end
  end
end

app/controllers/very_bests_controller.rb
class VeryBestsController < ApplicationController
  before_action :current_user_must_be_very_best_user,
                only: %i[edit update destroy]

  before_action :set_very_best, only: %i[show edit update destroy]

  def index
    @q = VeryBest.ransack(params[:q])
    @very_bests = @q.result(distinct: true).includes(:entree, :venue,
                                                     :user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @very_best = VeryBest.new
  end

  def edit; end

  def create
    @very_best = VeryBest.new(very_best_params)

    if @very_best.save
      message = "VeryBest was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @very_best, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @very_best.update(very_best_params)
      redirect_to @very_best, notice: "Very best was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @very_best.destroy
    message = "VeryBest was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to very_bests_url, notice: message
    end
  end

  private

  def current_user_must_be_very_best_user
    set_very_best
    unless current_user == @very_best.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_very_best
    @very_best = VeryBest.find(params[:id])
  end

  def very_best_params
    params.require(:very_best).permit(:notes, :dish_id, :venue_id, :user_id)
  end
end

app/views/very_bests/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Very Best #<%= very_best.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Notes</dt>
      <dd><%= very_best.notes %></dd>

      <dt>Dish</dt>
      <dd>
        <% if @very_best.entree.present? %>
          <%= link_to very_best.entree, very_best.entree %>
        <% end %>
      </dd>

      <dt>Venue</dt>
      <dd>
        <% if @very_best.venue.present? %>
          <%= link_to very_best.venue, very_best.venue %>
        <% end %>
      </dd>

      <dt>User</dt>
      <dd>
        <% if @very_best.user.present? %>
          <%= link_to very_best.user, very_best.user %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back very_best, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @very_best.user %>
          <%= link_to edit_very_best_url(very_best), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @very_best.user %>
          <%= link_to very_best, method: :delete, data: { confirm: "Do you really want to delete this very_best?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(very_best.updated_at) %> ago
  </div>
</div>

app/views/very_bests/_form.html.erb
<% was_validated = very_best.errors.any? %>

<%= form_with(model: very_best, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% note_class = "form-control" %>
    <% note_was_invalid = very_best.errors.include?(:note) %>

    <% if was_validated %>
      <% if note_was_invalid %>
        <% note_class << " is-invalid" %>
      <% else %>
        <% note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :notes %>
    <%= f.text_field :notes, class: note_class, placeholder: "Enter note" %>
    <% if note_was_invalid %>
      <% very_best.errors.full_messages_for(:note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dish_class = "form-control" %>
    <% dish_was_invalid = very_best.errors.include?(:dish) %>

    <% if was_validated %>
      <% if dish_was_invalid %>
        <% dish_class << " is-invalid" %>
      <% else %>
        <% dish_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dish_id %>
    <%= f.collection_select :dish_id, Dish.all, :id, :to_s, {}, class: "form-control" %>
    <% if dish_was_invalid %>
      <% very_best.errors.full_messages_for(:dish).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% venue_class = "form-control" %>
    <% venue_was_invalid = very_best.errors.include?(:venue) %>

    <% if was_validated %>
      <% if venue_was_invalid %>
        <% venue_class << " is-invalid" %>
      <% else %>
        <% venue_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :venue_id %>
    <%= f.collection_select :venue_id, Venue.all, :id, :to_s, {}, class: "form-control" %>
    <% if venue_was_invalid %>
      <% very_best.errors.full_messages_for(:venue).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/very_bests/_list_item.html.erb
<%= link_to very_best, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= very_best %>
    <small class="text-muted">
      <%= time_ago_in_words(very_best.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/very_bests/_very_bests_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "very_bests_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :notes_cont, "Notes contains" %>
    <%= f.text_field :notes_cont, :class => "form-control", :placeholder => "Notes contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :entree_name_cont, "Entree name contains" %>
    <%= f.text_field :entree_name_cont, :class => "form-control", :placeholder => "Entree name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :venue_name_cont, "Venue name contains" %>
    <%= f.text_field :venue_name_cont, :class => "form-control", :placeholder => "Venue name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_name_cont, "User name contains" %>
    <%= f.text_field :user_name_cont, :class => "form-control", :placeholder => "User name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/very_bests" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#very_bests_filters">
  Show filters
</a>

app/views/very_bests/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Very Best #<%= @very_best.id %>
      </h2>

      <div class="card-body">
        <%= render "form", very_best: @very_best %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/very_bests/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Very Bests

      <%= link_to new_very_best_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "very_bests/very_bests_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Very Bests

        <%= link_to new_very_best_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @very_bests, partial: "list_item", as: :very_best %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @very_bests, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/very_bests/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Very Best
      </h2>

      <div class="card-body">
        <%= render "form", very_best: @very_best %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/very_bests/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @very_best, partial: "card", as: :very_best %>
  </div>
</div>